import { defineConfig } from "vite"
import react from "@vitejs/plugin-react"
import { resolve } from "path"
import { VitePWA } from "vite-plugin-pwa"

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: "autoUpdate",
      strategies: "generateSW",
      injectRegister: "script",
      // Tell vite-plugin-pwa the manifest filename so it matches the
      // <link rel="manifest"> we put in index.html
      manifestFilename: "manifest.webmanifest",
      workbox: {
        globPatterns: ["**/*.{js,css,html,ico,png,svg,woff,woff2}"],
        navigateFallbackDenylist: [/^\/api\//, /^\/uploads\//, /^\/.well-known\//],
        runtimeCaching: [
          {
            // API calls: network-first, fall back to cache for 5 minutes
            urlPattern: /^https:\/\/portal\.bhabygroup\.co\.tz\/api\//,
            handler: "NetworkFirst",
            options: {
              cacheName: "api-cache",
              expiration: { maxEntries: 50, maxAgeSeconds: 300 },
              networkTimeoutSeconds: 10
            }
          },
          {
            // Uploaded images: cache-first (they don't change)
            urlPattern: /\/uploads\//,
            handler: "CacheFirst",
            options: {
              cacheName: "images-cache",
              expiration: { maxEntries: 200, maxAgeSeconds: 60 * 60 * 24 * 30 }
            }
          },
          {
            // Cloudinary images: cache-first
            urlPattern: /^https:\/\/res\.cloudinary\.com\//,
            handler: "CacheFirst",
            options: {
              cacheName: "cloudinary-cache",
              expiration: { maxEntries: 200, maxAgeSeconds: 60 * 60 * 24 * 30 }
            }
          }
        ]
      },
      manifest: {
        // id scopes the PWA identity — must match across updates
        id: "/",
        name: "E-Shop — BHABY GROUP LTD",
        short_name: "E-Shop",
        description: "Multi-vendor marketplace and seller dashboard by BHABY GROUP LTD",
        start_url: "/",
        scope: "/",
        display: "standalone",
        background_color: "#ffffff",
        theme_color: "#2563eb",
        orientation: "portrait-primary",
        lang: "en",
        categories: ["shopping", "business", "productivity"],
        icons: [
          // Standard favicon sizes
          {
            src: "/favicon.ico",
            sizes: "64x64 32x32 24x24 16x16",
            type: "image/x-icon"
          },
          // 192 — "any" purpose: used as-is, no clipping
          {
            src: "/icon-192.png",
            sizes: "192x192",
            type: "image/png",
            purpose: "any"
          },
          // 192 — maskable: Android adaptive icons (safe zone = center 80%)
          // Generated by scripts/gen-maskable-icons.cjs
          {
            src: "/icon-192-maskable.png",
            sizes: "192x192",
            type: "image/png",
            purpose: "maskable"
          },
          // 512 — "any" purpose
          {
            src: "/icon-512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "any"
          },
          // 512 — maskable
          {
            src: "/icon-512-maskable.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable"
          }
        ],
        shortcuts: [
          {
            name: "Marketplace",
            short_name: "Shop",
            description: "Browse all products",
            url: "/store",
            icons: [{ src: "/icon-192.png", sizes: "192x192", type: "image/png" }]
          },
          {
            name: "Seller Dashboard",
            short_name: "Dashboard",
            description: "Manage your store",
            url: "/dashboard",
            icons: [{ src: "/icon-192.png", sizes: "192x192", type: "image/png" }]
          },
          {
            name: "POS Terminal",
            short_name: "POS",
            description: "Process in-store sales",
            url: "/pos",
            icons: [{ src: "/icon-192.png", sizes: "192x192", type: "image/png" }]
          }
        ],
        // Screenshots are required by Google Play for the enhanced install UI.
        // Add real screenshots after capturing them from the running app.
        // Narrow = mobile (9:16 ratio), wide = desktop (16:9 ratio).
        screenshots: [
          {
            src: "/screenshots/mobile-store.png",
            sizes: "390x844",
            type: "image/png",
            form_factor: "narrow",
            label: "E-Shop Marketplace — browse products from local sellers"
          },
          {
            src: "/screenshots/mobile-dashboard.png",
            sizes: "390x844",
            type: "image/png",
            form_factor: "narrow",
            label: "Seller Dashboard — manage your store and track sales"
          },
          {
            src: "/screenshots/desktop-store.png",
            sizes: "1280x800",
            type: "image/png",
            form_factor: "wide",
            label: "E-Shop Marketplace on desktop"
          }
        ]
      },
      devOptions: {
        enabled: false
      }
    })
  ],
  resolve: {
    alias: {
      "@": resolve(__dirname, "./src"),
    }
  },
  base: '/',
  server: {
    port: 5173,
    host: "localhost",
    allowedHosts: ["localhost", "127.0.0.1"],
    proxy: {
      '/api': {
        target: 'http://localhost:3001',
        changeOrigin: true,
        secure: false
      }
    }
  },
  build: {
    outDir: 'dist',
    assetsDir: 'assets',
    sourcemap: false,
    // Split vendor libraries into separate cached chunks.
    // When app code changes, vendor chunks stay cached in the browser.
    rollupOptions: {
      output: {
        manualChunks: {
          // React core — changes almost never
          'vendor-react': ['react', 'react-dom', 'react-router-dom'],
          // Radix UI primitives — large, changes rarely
          'vendor-radix': [
            '@radix-ui/react-dialog',
            '@radix-ui/react-tabs',
            '@radix-ui/react-select',
            '@radix-ui/react-dropdown-menu',
            '@radix-ui/react-toast',
            '@radix-ui/react-popover',
            '@radix-ui/react-accordion',
            '@radix-ui/react-alert-dialog',
          ],
          // Charts — heavy, only used on Reports/Dashboard
          'vendor-charts': ['recharts'],
          // Icons — large icon set
          'vendor-icons': ['lucide-react'],
        }
      }
    }
  }
})
