import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

// Define available languages
export type Language = "en" | "sw";

// Define the context type
type LanguageContextType = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

// Create the context with default values
const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
});

// Define props for the provider component
interface LanguageProviderProps {
  children: ReactNode;
  defaultLanguage?: Language;
  storageKey?: string;
}

// Create translations object
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.menu": "Menu",
    "nav.dashboard": "Dashboard",
    "nav.pos": "Point of Sale",
    "nav.inventory": "Inventory",
    "nav.staff": "Staff",
    "nav.reports": "Reports",
    "nav.expenses": "Expenses",
    "nav.customers": "Customers",
    "nav.settings": "Settings",
    
    // Common actions
    "action.add": "Add",
    "action.edit": "Edit",
    "action.delete": "Delete",
    "action.save": "Save",
    "action.cancel": "Cancel",
    "action.search": "Search",
    "action.filter": "Filter",
    "action.logout": "Logout",
    "action.restock": "Restock",
    
    // Auth
    "auth.login": "Login",
    "auth.register": "Register",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.forgotPassword": "Forgot Password",
    
    // Inventory
    "inventory.title": "Inventory Management",
    "inventory.product": "Product",
    "inventory.quantity": "Quantity",
    "inventory.price": "Price",
    "inventory.category": "Category",
    "inventory.supplier": "Supplier",
    "inventory.addProduct": "Add Product",
    "inventory.editProduct": "Edit Product",
    "inventory.count": "Inventory Count",
    "inventory.totalProducts": "Total Products",
    "inventory.totalItems": "Total Items",
    "inventory.value": "Inventory Value",
    "inventory.lowStock": "Low Stock Items",
    
    // Actions
    "action.export": "Export",
    "action.exportOptions": "Export Options",
    "action.exportAsCsv": "Export as CSV",
    "action.exportAsPdf": "Export as PDF",
    
    // Tabs
    "tabs.products": "Products",
    "tabs.alerts": "Low Stock Alerts",
    "tabs.history": "Restock History",
    "tabs.analytics": "Analytics",
    
    // POS
    "pos.title": "Point of Sale",
    "pos.cart": "Cart",
    "pos.checkout": "Checkout",
    "pos.total": "Total",
    "pos.payment": "Payment",
    "pos.change": "Change",
    "pos.receipt": "Receipt",
    "pos.products": "Products",
    "pos.searchProducts": "Search products by name or scan barcode...",
    "pos.recentSales": "Recent Sales",
    "pos.shoppingCart": "Shopping Cart",
    "pos.selectCustomer": "Select customer",
    "pos.addCustomer": "Add New Customer",
    "pos.customerName": "Name",
    "pos.customerType": "Customer Type",
    "pos.email": "Email",
    "pos.phone": "Phone",
    "pos.creditLimit": "Credit Limit",
    "pos.discountAmount": "Discount amount",
    "pos.taxRate": "Tax rate (%)",
    "pos.processPayment": "Process Payment",
    "pos.paymentMethod": "Select payment method",
    "pos.amountPaid": "Amount Paid",
    "pos.payFullAmount": "Pay Full Amount",
    "pos.findProduct": "Find Product",
    "pos.scanBarcode": "Scan Product Barcode",
    
    // Settings
    "settings.title": "System Settings",
    "settings.general": "General",
    "settings.users": "Users",
    "settings.backup": "Backup",
    "settings.language": "Language",
    "settings.theme": "Theme",
    
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.loading": "Loading...",
    "dashboard.dailyRevenue": "Daily Revenue",
    "dashboard.weeklyRevenue": "Weekly Revenue",
    "dashboard.monthlyRevenue": "Monthly Revenue",
    "dashboard.dailySales": "Daily Sales",
    "dashboard.lowStockAlerts": "Low Stock Alerts",
    "dashboard.stock": "Stock",
    "dashboard.failedToFetch": "Failed to fetch dashboard data",
    
    // Expenses
    "expenses.title": "Expenses",
    "expenses.refreshData": "Refresh data",
    "expenses.selectDateRange": "Select date range",
    "expenses.allTime": "All Time",
    "expenses.today": "Today",
    "expenses.thisWeek": "This Week",
    "expenses.thisMonth": "This Month",
    "expenses.customRange": "Custom Range",
    "expenses.to": "to",
    "expenses.addExpense": "Add Expense",
    "expenses.filters": "Filters:",
    "expenses.category": "Category",
    "expenses.allCategories": "All Categories",
    "expenses.utilities": "Utilities",
    "expenses.rent": "Rent",
    "expenses.salary": "Salary",
    "expenses.supplies": "Supplies",
    "expenses.maintenance": "Maintenance",
    "expenses.inventoryAdjustments": "Inventory Adjustments",
    "expenses.inventoryOverageIncome": "Inventory Overage Income",
    "expenses.other": "Other",
    "expenses.resetFilter": "Reset Filter",
    "expenses.totalExpenses": "Total Expenses",
    "expenses.income": "Income",
    "expenses.expenseHistory": "Expense History",
    "expenses.date": "Date",
    "expenses.description": "Description",
    "expenses.amount": "Amount",
    "expenses.noExpensesFound": "No expenses found for the selected filters",
    "expenses.enterDescription": "Enter expense description",
    "expenses.enterAmount": "Enter amount",
    "expenses.selectCategory": "Select category",
    "expenses.cancel": "Cancel",
    "expenses.fillAllFields": "Please fill all required fields",
    "expenses.expenseAdded": "Expense added successfully",
    "expenses.failedToAdd": "Failed to add expense",
    "expenses.failedToFetch": "Failed to fetch expenses",
    
    // Language
    "language.english": "English",
    "language.swahili": "Swahili",
    
    // Theme
    "theme.light": "Light",
    "theme.dark": "Dark",
    
    // Staff
    "staff.title": "Staff Management",
    "staff.subtitle": "Manage staff members and their permissions",
    "staff.name": "Name",
    "staff.email": "Email",
    "staff.role": "Role",
    "staff.status": "Status",
    "staff.created": "Created",
    "staff.actions": "Actions",
    "staff.edit": "Edit",
    "staff.delete": "Delete",
    "staff.approved": "Approved",
    "staff.pending": "Pending",
    "staff.noStaffFound": "No staff members found",
    "staff.deleteConfirmTitle": "Are you sure?",
    "staff.deleteConfirmDescription": "This action cannot be undone. This will permanently delete the staff member and remove their access to the system.",
    // Reports
    "reports.title": "Reports & Analytics",
    "reports.refresh": "Refresh data",
    "reports.dateRange": "Select date range",
    "reports.allTime": "All Time",
    "reports.today": "Today",
    "reports.thisWeek": "This Week",
    "reports.thisMonth": "This Month",
    "reports.customRange": "Custom Range",
    "reports.to": "to",
    "reports.loading": "Loading analytics data...",
    "reports.overview": "Overview",
    "reports.profitLoss": "Profit & Loss",
    "reports.taxReports": "Tax Reports",
    "reports.inventory": "Inventory",
    "reports.dailyRevenue": "Daily Revenue",
    "reports.weeklyRevenue": "Weekly Revenue",
    "reports.monthlyRevenue": "Monthly Revenue",
    "reports.salesTrend": "Sales Trend",
    "reports.popularItems": "Popular Items",
    "reports.product": "Product",
    "reports.sales": "Sales",
    "reports.noSalesData": "No sales data available",
    "reports.dailyTax": "Daily Tax Collected",
    "reports.weeklyTax": "Weekly Tax Collected",
    "reports.monthlyTax": "Monthly Tax Collected",
    "reports.taxSummary": "Tax Summary",
    "reports.period": "Period",
    "reports.grossSales": "Gross Sales",
    "reports.netSales": "Net Sales",
    "reports.taxCollected": "Tax Collected",
    "reports.taxRate": "Tax Rate",
    "reports.totalInventoryValue": "Total Inventory Value",
    "reports.totalItemsInStock": "Total Items in Stock",
    "reports.uniqueProducts": "Unique Products",
    "reports.lowStockAlerts": "Low Stock Alerts",
    "reports.category": "Category",
    "reports.currentStock": "Current Stock",
    "reports.reorderPoint": "Reorder Point",
    "reports.noLowStockItems": "No low stock items",
    "reports.stockValueByCategory": "Stock Value by Category",
    "reports.stockByCategory": "Stock by Category",
    "reports.noCategoryData": "No category data available",
    "reports.revenue": "Revenue",
    "reports.grossProfit": "Gross Profit",
    "reports.netProfit": "Net Profit",
    "reports.revenueBreakdown": "Revenue Breakdown",
    "reports.expenseBreakdown": "Expense Breakdown",
    "reports.profitLossStatement": "Profit & Loss Statement",
    "reports.item": "Item",
    "reports.currentPeriod": "Current Period",
    "reports.previousPeriod": "Previous Period",
    "reports.change": "Change",
    "reports.costOfGoods": "Cost of Goods",
    "reports.expenses": "Expenses",
    
    // Customers
    "customers.title": "Customers",
    "customers.addCustomer": "Add Customer",
    "customers.management": "Customer Management",
    "customers.searchPlaceholder": "Search customers by name, email, or phone...",
    "customers.filterByType": "Filter by type",
    "customers.allCustomers": "All Customers",
    "customers.creditCustomers": "Credit Customers",
    "customers.cashCustomers": "Cash Customers",
    "customers.name": "Name",
    "customers.type": "Type",
    "customers.contact": "Contact",
    "customers.creditLimit": "Credit Limit",
    "customers.currentCredit": "Current Credit",
    "customers.actions": "Actions",
    "customers.noCustomersFound": "No customers found",
    "customers.details": "Customer Details",
    "customers.customerDetails": "Customer Details",
    "customers.transactionHistory": "Transaction History",
    "customers.email": "Email",
    "customers.phone": "Phone",
    "customers.availableCredit": "Available Credit",
    "customers.creditUsage": "Credit Usage",
    "customers.createdAt": "Created At",
    "customers.lastUpdated": "Last Updated",
    "customers.recordPayment": "Record Payment",
    "customers.recentTransactions": "Recent Transactions",
    "customers.noTransactions": "No transactions found for this customer",
    "customers.date": "Date",
    "customers.items": "Items",
    "customers.total": "Total",
    "customers.paymentMethod": "Payment Method",
    "customers.close": "Close",
    "customers.editCustomer": "Edit Customer",
    "customers.customerName": "Name *",
    "customers.customerType": "Customer Type",
    "customers.selectCustomerType": "Select customer type",
    "customers.cash": "Cash",
    "customers.credit": "Credit",
    "customers.emailAddress": "Email",
    "customers.phoneNumber": "Phone",
    "customers.cancel": "Cancel",
    "customers.saveChanges": "Save Changes",
    "customers.deleteCustomer": "Delete Customer",
    "customers.deleteConfirmation": "Are you sure you want to delete this customer?",
    "customers.deleteWarning": "This action cannot be undone. All customer data will be permanently removed.",
    "customers.recordCustomerPayment": "Record Customer Payment",
    "customers.paymentInstructions": "Enter a negative value to record a payment (reduce credit). For example, enter \"-100\" to record a payment of $100.",
    "customers.amount": "Amount",
    "customers.addNewCustomer": "Add New Customer",
    "customers.customerNameRequired": "Customer name is required",
    "customers.enterValidAmount": "Please enter a valid amount",
    "customers.enterNegativeAmount": "Please enter a negative amount to record a payment",
    "customers.paymentRecorded": "Payment of {amount} recorded successfully",
    "customers.customerUpdated": "Customer updated successfully",
    "customers.customerDeleted": "Customer deleted successfully",
    "customers.customerAdded": "Customer added successfully",
    "customers.failedToFetch": "Failed to fetch customers",
    "customers.failedToFetchSales": "Failed to fetch customer sales",
    "customers.failedToUpdate": "Failed to update customer",
    "customers.failedToDelete": "Failed to delete customer",
    "customers.failedToUpdateCredit": "Failed to update customer credit",
    "customers.failedToAdd": "Failed to add customer",
    
    // Settings (continued)
    "settings.saveAll": "Save All Settings",
    "settings.businessInfo": "Business Information",
    "settings.taxSettings": "Tax Settings",
    "settings.receiptSettings": "Receipt Settings",
    "settings.paymentMethods": "Payment Methods",
    "settings.businessName": "Business Name",
    "settings.address": "Address",
    "settings.phoneNumber": "Phone Number",
    "settings.emailAddress": "Email Address",
    "settings.taxId": "Tax ID / TIN Number",
    "settings.logo": "Logo (URL)",
    "settings.enableTax": "Enable Tax",
    "settings.defaultTaxRate": "Default Tax Rate (%)",
    "settings.taxIncluded": "Tax Included in Price",
    "settings.showLogo": "Show Logo on Receipt",
    "settings.showTaxId": "Show Tax ID on Receipt",
    "settings.receiptPrefix": "Receipt Number Prefix",
    "settings.footerText": "Receipt Footer Text",
    "settings.printAutomatically": "Print Receipt Automatically",
    "settings.acceptCash": "Accept Cash Payments",
    "settings.acceptCard": "Accept Card Payments",
    "settings.acceptMobile": "Accept Mobile Money",
    "settings.acceptCredit": "Accept Credit Accounts",
    "settings.defaultPayment": "Default Payment Method",
    "settings.selectDefaultPayment": "Select default payment method",
    "settings.cash": "Cash",
    "settings.card": "Card",
    "settings.mobile": "Mobile Money",
    "settings.credit": "Credit",
    "settings.settingsSaved": "Settings saved successfully",
    "settings.failedToLoad": "Failed to load settings. Using default values.",
    "settings.failedToSave": "Failed to save settings",
    
    
    // System
    "system.title": "Dukani System",
  },
  sw: {
    // Navigation
    "nav.menu": "Menyu",
    "nav.dashboard": "Dashibodi",
    "nav.pos": "Sehemu ya Mauzo",
    "nav.inventory": "Bidhaa",
    "nav.staff": "Wafanyakazi",
    "nav.reports": "Ripoti",
    "nav.expenses": "Matumizi",
    "nav.customers": "Wateja",
    "nav.settings": "Mipangilio",
    
    // Common actions
    "action.add": "Ongeza",
    "action.edit": "Hariri",
    "action.delete": "Futa",
    "action.save": "Hifadhi",
    "action.cancel": "Ghairi",
    "action.search": "Tafuta",
    "action.filter": "Chuja",
    "action.logout": "Toka",
    "action.restock": "Ongeza Bidhaa Zaidi",
    
    // Auth
    "auth.login": "Ingia",
    "auth.register": "Jiandikishe",
    "auth.email": "Barua pepe",
    "auth.password": "Nywila",
    "auth.forgotPassword": "Umesahau Nywila",
    
    // Inventory
    "inventory.title": "Usimamizi wa Bidhaa",
    "inventory.product": "Bidhaa",
    "inventory.quantity": "Idadi",
    "inventory.price": "Bei",
    "inventory.category": "Kategoria",
    "inventory.supplier": "Msambazaji",
    "inventory.addProduct": "Ongeza Bidhaa",
    "inventory.editProduct": "Hariri Bidhaa",
    "inventory.count": "Hesabu ya Bidhaa",
    "inventory.totalProducts": "Jumla ya Bidhaa",
    "inventory.totalItems": "Jumla ya Vitu",
    "inventory.value": "Thamani ya Bidhaa",
    "inventory.lowStock": "Bidhaa Zinazopungua",
    
    // Actions
    "action.export": "Hamisha",
    "action.exportOptions": "Chaguo za Kuhamisha",
    "action.exportAsCsv": "Hamisha kama CSV",
    "action.exportAsPdf": "Hamisha kama PDF",
    
    // Tabs
    "tabs.products": "Bidhaa",
    "tabs.alerts": "Tahadhari za Bidhaa Zinazopungua",
    "tabs.history": "Historia ya Kuongeza Bidhaa",
    "tabs.analytics": "Uchambuzi",
    
    // POS
    "pos.title": "Sehemu ya Mauzo",
    "pos.cart": "Kikapu",
    "pos.checkout": "Lipa",
    "pos.total": "Jumla",
    "pos.payment": "Malipo",
    "pos.change": "Chenji",
    "pos.receipt": "Risiti",
    "pos.products": "Bidhaa",
    "pos.searchProducts": "Tafuta bidhaa kwa jina au skani msimbo...",
    "pos.recentSales": "Mauzo ya Hivi Karibuni",
    "pos.shoppingCart": "Kikapu cha Ununuzi",
    "pos.selectCustomer": "Chagua mteja",
    "pos.addCustomer": "Ongeza Mteja Mpya",
    "pos.customerName": "Jina",
    "pos.customerType": "Aina ya Mteja",
    "pos.email": "Barua pepe",
    "pos.phone": "Simu",
    "pos.creditLimit": "Kikomo cha Mkopo",
    "pos.discountAmount": "Kiasi cha punguzo",
    "pos.taxRate": "Kiwango cha kodi (%)",
    "pos.processPayment": "Fanya Malipo",
    "pos.paymentMethod": "Chagua njia ya malipo",
    "pos.amountPaid": "Kiasi Kilicholipwa",
    "pos.payFullAmount": "Lipa Kiasi Kamili",
    "pos.findProduct": "Tafuta Bidhaa",
    "pos.scanBarcode": "Skani Msimbo wa Bidhaa",
    
    // Settings
    "settings.title": "Mipangilio ya Mfumo",
    "settings.general": "Jumla",
    "settings.users": "Watumiaji",
    "settings.backup": "Hifadhi Nakala",
    "settings.language": "Lugha",
    "settings.theme": "Mandhari",
    
    // Language
    "language.english": "Kiingereza",
    "language.swahili": "Kiswahili",
    
    // Theme
    "theme.light": "Mwanga",
    "theme.dark": "Giza",
    
    // Dashboard
    "dashboard.title": "Dashibodi",
    "dashboard.loading": "Inapakia...",
    "dashboard.dailyRevenue": "Mapato ya Kila Siku",
    "dashboard.weeklyRevenue": "Mapato ya Wiki",
    "dashboard.monthlyRevenue": "Mapato ya Mwezi",
    "dashboard.dailySales": "Mauzo ya Kila Siku",
    "dashboard.lowStockAlerts": "Tahadhari za Bidhaa Zinazopungua",
    "dashboard.stock": "Bidhaa",
    "dashboard.failedToFetch": "Imeshindwa kupata data ya dashibodi",
    
    // Expenses
    "expenses.title": "Matumizi",
    "expenses.refreshData": "Onyesha upya data",
    "expenses.selectDateRange": "Chagua kipindi cha tarehe",
    "expenses.allTime": "Wakati Wote",
    "expenses.today": "Leo",
    "expenses.thisWeek": "Wiki Hii",
    "expenses.thisMonth": "Mwezi Huu",
    "expenses.customRange": "Kipindi Maalum",
    "expenses.to": "hadi",
    "expenses.addExpense": "Ongeza Matumizi",
    "expenses.filters": "Vichujio:",
    "expenses.category": "Kategoria",
    "expenses.allCategories": "Kategoria Zote",
    "expenses.utilities": "Huduma",
    "expenses.rent": "Kodi",
    "expenses.salary": "Mshahara",
    "expenses.supplies": "Vifaa",
    "expenses.maintenance": "Matengenezo",
    "expenses.inventoryAdjustments": "Marekebisho ya Bidhaa",
    "expenses.inventoryOverageIncome": "Mapato ya Ziada ya Bidhaa",
    "expenses.other": "Nyinginezo",
    "expenses.resetFilter": "Ondoa Kichujio",
    "expenses.totalExpenses": "Jumla ya Matumizi",
    "expenses.income": "Mapato",
    "expenses.expenseHistory": "Historia ya Matumizi",
    "expenses.date": "Tarehe",
    "expenses.description": "Maelezo",
    "expenses.amount": "Kiasi",
    "expenses.noExpensesFound": "Hakuna matumizi yaliyopatikana kwa vichujio vilivyochaguliwa",
    "expenses.enterDescription": "Ingiza maelezo ya matumizi",
    "expenses.enterAmount": "Ingiza kiasi",
    "expenses.selectCategory": "Chagua kategoria",
    "expenses.cancel": "Ghairi",
    "expenses.fillAllFields": "Tafadhali jaza sehemu zote zinazohitajika",
    "expenses.expenseAdded": "Matumizi yameongezwa kwa mafanikio",
    "expenses.failedToAdd": "Imeshindwa kuongeza matumizi",
    "expenses.failedToFetch": "Imeshindwa kupata matumizi",
    
    // Staff
    "staff.title": "Usimamizi wa Wafanyakazi",
    "staff.subtitle": "Simamia wafanyakazi na ruhusa zao",
    "staff.name": "Jina",
    "staff.email": "Barua pepe",
    "staff.role": "Wajibu",
    "staff.status": "Hali",
    "staff.created": "Imeundwa",
    "staff.actions": "Vitendo",
    "staff.edit": "Hariri",
    "staff.delete": "Futa",
    "staff.approved": "Imeidhinishwa",
    "staff.pending": "Inasubiri",
    "staff.noStaffFound": "Hakuna wafanyakazi waliopatikana",
    "staff.deleteConfirmTitle": "Una uhakika?",
    "staff.deleteConfirmDescription": "Kitendo hiki hakiwezi kutenduliwa. Kitafuta mfanyakazi huyu kabisa na kuondoa ufikiaji wao kwenye mfumo.",
    
    // Reports
    "reports.title": "Ripoti na Uchambuzi",
    "reports.refresh": "Onyesha upya data",
    "reports.dateRange": "Chagua kipindi cha tarehe",
    "reports.allTime": "Wakati Wote",
    "reports.today": "Leo",
    "reports.thisWeek": "Wiki Hii",
    "reports.thisMonth": "Mwezi Huu",
    "reports.customRange": "Kipindi Maalum",
    "reports.to": "hadi",
    "reports.loading": "Inapakia data ya uchambuzi...",
    "reports.overview": "Muhtasari",
    "reports.profitLoss": "Faida na Hasara",
    "reports.taxReports": "Ripoti za Kodi",
    "reports.inventory": "Bidhaa",
    "reports.dailyRevenue": "Mapato ya Kila Siku",
    "reports.weeklyRevenue": "Mapato ya Wiki",
    "reports.monthlyRevenue": "Mapato ya Mwezi",
    "reports.salesTrend": "Mwelekeo wa Mauzo",
    "reports.popularItems": "Bidhaa Maarufu",
    "reports.product": "Bidhaa",
    "reports.sales": "Mauzo",
    "reports.noSalesData": "Hakuna data ya mauzo",
    "reports.dailyTax": "Kodi Iliyokusanywa Kila Siku",
    "reports.weeklyTax": "Kodi Iliyokusanywa Wiki",
    "reports.monthlyTax": "Kodi Iliyokusanywa Mwezi",
    "reports.taxSummary": "Muhtasari wa Kodi",
    "reports.period": "Kipindi",
    "reports.grossSales": "Mauzo Ghafi",
    "reports.netSales": "Mauzo Halisi",
    "reports.taxCollected": "Kodi Iliyokusanywa",
    "reports.taxRate": "Kiwango cha Kodi",
    "reports.totalInventoryValue": "Thamani ya Bidhaa Zote",
    "reports.totalItemsInStock": "Jumla ya Bidhaa Zilizopo",
    "reports.uniqueProducts": "Bidhaa za Kipekee",
    "reports.lowStockAlerts": "Tahadhari za Bidhaa Zinazopungua",
    "reports.category": "Kategoria",
    "reports.currentStock": "Bidhaa Zilizopo",
    "reports.reorderPoint": "Kiwango cha Kuagiza Upya",
    "reports.noLowStockItems": "Hakuna bidhaa zinazopungua",
    "reports.stockValueByCategory": "Thamani ya Bidhaa kwa Kategoria",
    "reports.stockByCategory": "Bidhaa kwa Kategoria",
    "reports.noCategoryData": "Hakuna data ya kategoria",
    "reports.revenue": "Mapato",
    "reports.grossProfit": "Faida Ghafi",
    "reports.netProfit": "Faida Halisi",
    "reports.revenueBreakdown": "Mgawanyo wa Mapato",
    "reports.expenseBreakdown": "Mgawanyo wa Matumizi",
    "reports.profitLossStatement": "Taarifa ya Faida na Hasara",
    "reports.item": "Kipengee",
    "reports.currentPeriod": "Kipindi cha Sasa",
    "reports.previousPeriod": "Kipindi Kilichopita",
    "reports.change": "Mabadiliko",
    "reports.costOfGoods": "Gharama ya Bidhaa",
    "reports.expenses": "Matumizi",
    
    // Customers
    "customers.title": "Wateja",
    "customers.addCustomer": "Ongeza Mteja",
    "customers.management": "Usimamizi wa Wateja",
    "customers.searchPlaceholder": "Tafuta wateja kwa jina, barua pepe, au simu...",
    "customers.filterByType": "Chuja kwa aina",
    "customers.allCustomers": "Wateja Wote",
    "customers.creditCustomers": "Wateja wa Mkopo",
    "customers.cashCustomers": "Wateja wa Fedha Taslimu",
    "customers.name": "Jina",
    "customers.type": "Aina",
    "customers.contact": "Mawasiliano",
    "customers.creditLimit": "Kikomo cha Mkopo",
    "customers.currentCredit": "Mkopo wa Sasa",
    "customers.actions": "Vitendo",
    "customers.noCustomersFound": "Hakuna wateja waliopatikana",
    "customers.details": "Maelezo ya Mteja",
    "customers.customerDetails": "Maelezo ya Mteja",
    "customers.transactionHistory": "Historia ya Miamala",
    "customers.email": "Barua pepe",
    "customers.phone": "Simu",
    "customers.availableCredit": "Mkopo Uliopo",
    "customers.creditUsage": "Matumizi ya Mkopo",
    "customers.createdAt": "Imeundwa",
    "customers.lastUpdated": "Imesasishwa Mwisho",
    "customers.recordPayment": "Rekodi Malipo",
    "customers.recentTransactions": "Miamala ya Hivi Karibuni",
    "customers.noTransactions": "Hakuna miamala iliyopatikana kwa mteja huyu",
    "customers.date": "Tarehe",
    "customers.items": "Vitu",
    "customers.total": "Jumla",
    "customers.paymentMethod": "Njia ya Malipo",
    "customers.close": "Funga",
    "customers.editCustomer": "Hariri Mteja",
    "customers.customerName": "Jina *",
    "customers.customerType": "Aina ya Mteja",
    "customers.selectCustomerType": "Chagua aina ya mteja",
    "customers.cash": "Fedha Taslimu",
    "customers.credit": "Mkopo",
    "customers.emailAddress": "Barua pepe",
    "customers.phoneNumber": "Simu",
    "customers.cancel": "Ghairi",
    "customers.saveChanges": "Hifadhi Mabadiliko",
    "customers.deleteCustomer": "Futa Mteja",
    "customers.deleteConfirmation": "Je, una uhakika unataka kufuta mteja huyu?",
    "customers.deleteWarning": "Kitendo hiki hakiwezi kutenduliwa. Data zote za mteja zitaondolewa kabisa.",
    "customers.recordCustomerPayment": "Rekodi Malipo ya Mteja",
    "customers.paymentInstructions": "Ingiza thamani hasi ili kurekodi malipo (punguza mkopo). Kwa mfano, ingiza \"-100\" ili kurekodi malipo ya $100.",
    "customers.amount": "Kiasi",
    "customers.addNewCustomer": "Ongeza Mteja Mpya",
    "customers.customerNameRequired": "Jina la mteja linahitajika",
    "customers.enterValidAmount": "Tafadhali ingiza kiasi halali",
    "customers.enterNegativeAmount": "Tafadhali ingiza kiasi hasi ili kurekodi malipo",
    "customers.paymentRecorded": "Malipo ya {amount} yameandikishwa kwa mafanikio",
    "customers.customerUpdated": "Mteja amesasishwa kwa mafanikio",
    "customers.customerDeleted": "Mteja amefutwa kwa mafanikio",
    "customers.customerAdded": "Mteja ameongezwa kwa mafanikio",
    "customers.failedToFetch": "Imeshindwa kupata wateja",
    "customers.failedToFetchSales": "Imeshindwa kupata mauzo ya mteja",
    "customers.failedToUpdate": "Imeshindwa kusasisha mteja",
    "customers.failedToDelete": "Imeshindwa kufuta mteja",
    "customers.failedToUpdateCredit": "Imeshindwa kusasisha mkopo wa mteja",
    "customers.failedToAdd": "Imeshindwa kuongeza mteja",
    
    // Settings (continued)
    "settings.saveAll": "Hifadhi Mipangilio Yote",
    "settings.businessInfo": "Taarifa za Biashara",
    "settings.taxSettings": "Mipangilio ya Kodi",
    "settings.receiptSettings": "Mipangilio ya Risiti",
    "settings.paymentMethods": "Njia za Malipo",
    "settings.businessName": "Jina la Biashara",
    "settings.address": "Anwani",
    "settings.phoneNumber": "Namba ya Simu",
    "settings.emailAddress": "Anwani ya Barua Pepe",
    "settings.taxId": "Namba ya Kodi / TIN",
    "settings.logo": "Nembo (URL)",
    "settings.enableTax": "Wezesha Kodi",
    "settings.defaultTaxRate": "Kiwango cha Kodi cha Kawaida (%)",
    "settings.taxIncluded": "Kodi Imejumuishwa katika Bei",
    "settings.showLogo": "Onyesha Nembo kwenye Risiti",
    "settings.showTaxId": "Onyesha Namba ya Kodi kwenye Risiti",
    "settings.receiptPrefix": "Kiambishi cha Namba ya Risiti",
    "settings.footerText": "Maandishi ya Kijachini ya Risiti",
    "settings.printAutomatically": "Chapisha Risiti Kiotomatiki",
    "settings.acceptCash": "Kubali Malipo ya Fedha Taslimu",
    "settings.acceptCard": "Kubali Malipo ya Kadi",
    "settings.acceptMobile": "Kubali Pesa za Simu",
    "settings.acceptCredit": "Kubali Akaunti za Mkopo",
    "settings.defaultPayment": "Njia ya Malipo ya Kawaida",
    "settings.selectDefaultPayment": "Chagua njia ya malipo ya kawaida",
    "settings.cash": "Fedha Taslimu",
    "settings.card": "Kadi",
    "settings.mobile": "Pesa za Simu",
    "settings.credit": "Mkopo",
    "settings.settingsSaved": "Mipangilio imehifadhiwa kwa mafanikio",
    "settings.failedToLoad": "Imeshindwa kupakia mipangilio. Inatumia thamani za kawaida.",
    "settings.failedToSave": "Imeshindwa kuhifadhi mipangilio",
    
    // System
    "system.title": "Mfumo wa Dukani",
  }
};

// Create the provider component
export function LanguageProvider({
  children,
  defaultLanguage = "en",
  storageKey = "app-language",
}: LanguageProviderProps) {
  // Initialize state with the default language or the one from localStorage
  const [language, setLanguageState] = useState<Language>(() => {
    // Check if we're in the browser and if there's a saved preference
    if (typeof window !== "undefined") {
      const savedLanguage = localStorage.getItem(storageKey);
      return (savedLanguage as Language) || defaultLanguage;
    }
    return defaultLanguage;
  });

  // Update the language in localStorage when it changes
  useEffect(() => {
    localStorage.setItem(storageKey, language);
    // Update the lang attribute on the html element
    document.documentElement.lang = language;
  }, [language, storageKey]);

  // Function to set the language
  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
  };

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// Custom hook to use the language context
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}